### PR TITLE
French translation implementation 

### LINKED ISSUE #50: Include localization for French
Implement localization for French in Django.

### PR DESCRIPTION
**Pull request by sylviamclaughlin**
# Summary | Résumé

Implemented French language translations for the whole app. All the messages and text should be translated and you can switch languages in the menu. Sorry for the massive PR!

Closes #50 

Screen Shot 2023-03-22 at 5 11 39 PM
Screen Shot 2023-03-22 at 5 12 03 PM

### CODE REVIEW

**Review by gcharest — CHANGES_REQUESTED** [review]
A couple little issues I had:

- Authenticating with Google SSO threw an error
- Switching language automatically navigates back home (doesn't stay on current view)

**Comment by gcharest** [comment]
> Works really well! Nice work! I added four valid URL callbacks to Google OAuth to account for the new language namespacing, ex `http://localhost:8000/en/accounts/google/login/callback/`
> 
> The only other recommendation I would have is to capitalize the F in `français` at the top of the page

Ha! The updated callback URI should solve my first issue! 🎉  Testing right away!

**Comment by gcharest** [comment]
Confirming that the updated callback URIs have solved the Google SSO issue for me!

Not sure if the auto navigation to Home on language toggle should happen or not.

**Comment by sylviamclaughlin** [comment]
> Works really well! Nice work! I added four valid URL callbacks to Google OAuth to account for the new language namespacing, ex `http://localhost:8000/en/accounts/google/login/callback/`
> 
> The only other recommendation I would have is to capitalize the F in `français` at the top of the page

@maxneuvians - I have changed the code so that now it appears as Français

**Comment by sylviamclaughlin** [comment]
> Confirming that the updated callback URIs have solved the Google SSO issue for me!
> 
> Not sure if the auto navigation to Home on language toggle should happen or not.

@gcharest - I have changed the code so that now when switching languages, you always stay on the same page that you are currently at.

**Review by gcharest — APPROVED** [review]
Works as expected! Love that it's fully bilingual now :D

**Pull request merged**
